apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mercure.fullname" . }}
  labels:
    {{- include "mercure.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mercure.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mercure.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mercure.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.dev }}
          command: ["caddy"]
          args: ["run", "--config", "/etc/caddy/dev.Caddyfile", "--adapter", "caddyfile"]
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_NAME
              value: :{{ .Values.service.targetPort }}
            - name: GLOBAL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mercure.fullname" . }}
                  key: global-options
            - name: CADDY_EXTRA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ include "mercure.fullname" . }}
                  key: caddy-extra-config
            - name: CADDY_SERVER_EXTRA_DIRECTIVES
              valueFrom:
                secretKeyRef:
                  name: {{ include "mercure.secretName" . }}
                  key: caddy-extra-directives
            - name: MERCURE_TRANSPORT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "mercure.secretName" . }}
                  key: transport-url
            - name: MERCURE_PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mercure.secretName" . }}
                  key: publisher-jwt-key
            - name: MERCURE_PUBLISHER_JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mercure.fullname" . }}
                  key: publisher-jwt-alg
            - name: MERCURE_SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mercure.secretName" . }}
                  key: subscriber-jwt-key
            - name: MERCURE_SUBSCRIBER_JWT_ALG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mercure.fullname" . }}
                  key: subscriber-jwt-alg
            - name: MERCURE_EXTRA_DIRECTIVES
              valueFrom:
                secretKeyRef:
                  name: {{ include "mercure.secretName" . }}
                  key: extra-directives
            - name: MERCURE_LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ include "mercure.secretName" . }}
                  key: license
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: /data
              name: mercure-data
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["curl", "-XPOST", "http://localhost:2019/stop"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: mercure-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "mercure.fullname" .) }}
      {{- end }}
