name: Lint Docs and Non-Go Code
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_GO: false
          VALIDATE_PHP_PHPCS: false
          VALIDATE_KUBERNETES_CONFORM: false
          KUBERNETES_KUBEVAL: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
